### ISSUE TITLE
Name clash?

### ISSUE THREAD

**Issue by vladimir-kozyrev** [patoarvizu/terraform-provider-openvpncloud#6]
Hey @patoarvizu! Thank you for coming up with this provider.
It looks like there is name clash between the Terraform Registry and GitHub.

Here is my `provider.tf` file which is the only file in my local directory.
```hcl
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
  required_providers {
    openvpn-cloud = {
      source = "patoarvizu/openvpn-cloud"
      version = "0.0.3"
    }
  }
}
```

When I run `TF_LOG=DEBUG terraform init`, I get
```
Initializing provider plugins...
- Finding patoarvizu/openvpn-cloud versions matching "0.0.3"...
2022-03-21T23:09:37.817+0300 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2022-03-21T23:09:38.115+0300 [DEBUG] GET https://registry.terraform.io/v1/providers/patoarvizu/openvpn-cloud/versions
2022-03-21T23:09:38.391+0300 [DEBUG] GET https://registry.terraform.io/v1/providers/patoarvizu/openvpn-cloud/0.0.3/download/darwin/arm64
2022-03-21T23:09:38.616+0300 [DEBUG] GET https://github.com/patoarvizu/terraform-provider-openvpn-cloud/releases/download/v0.0.3/terraform-provider-openvpn-cloud_0.0.3_SHA256SUMS
╷
│ Error: Failed to install provider
│
│ Error while installing patoarvizu/openvpn-cloud v0.0.3: could not query provider registry for registry.terraform.io/patoarvizu/openvpn-cloud: failed to retrieve authentication
│ checksums for provider: 404 Not Found
```

It looks like the issue is caused by the difference in provider name.
At https://registry.terraform.io/providers/patoarvizu/openvpn-cloud/latest it is called openvpn-cloud with a dash.
And on GitHub it is called openvpncloud without a dash.

Note the last GET debug message above.
If you change openvpn-cloud_0.0.3_SHA256SUMS to openvpncloud_0.0.3_SHA256SUMS, then the file can be found and donwloaded.

If I am right and there is a name clash, could you update the provider name either here or on the registry side?

**Comment by patoarvizu** [comment]
Hey @vladimir-kozyrev, thanks for checking out the provider!

Yes, there is an issue where the provider was initially published incorrectly under `patoarvizu/openvpn-cloud`. There doesn't seem to be a mechanism for removing providers on the Terraform registry, which is why I haven't removed it. That was later fixed and published as [`patoarvizu/openvpncloud`](https://registry.terraform.io/providers/patoarvizu/openvpncloud/latest) which is the right one and the one you should set in your `required_providers`. Give that a try and let me know if it works for you.

**Comment by vladimir-kozyrev** [comment]
@patoarvizu oh, got it! It works as expected. Thanks!
